node('master'){

    stage 'Checkout'
    
    git url:
    
     

    
    def mvnHome= tool 'M3'
  


    stage 'Build'


    sh "${mvnHome}/bin/mvn clean package"
    step([$class: 'JUnitResultArchiver', testResults:'**/target/**/TEST*.xml'])
}

